#
# Copyright 2013-2022 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: JDL tests
concurrency:
  # Group PRs by head_ref, push to main branch by commit id, and others branch by ref.
  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [closed, opened, synchronize, reopened]
    branches:
      - '*'
permissions:
  contents: read
jobs:
  applications:
    name: ${{ matrix.audit-framework }} ${{ matrix.build-tool }}) ${{ matrix.suite }} (${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/app
    if: github.event.action != 'closed'
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        build-tool: [maven, gradle]
        audit-framework: [custom, javers]
        suite:
          - postgresql-mvc-jwt
    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - name: 'SETUP: create app folder'
        run: mkdir app
        working-directory: ${{ github.workspace }}
      - name: 'SETUP: checkout generator-jhipster-entity-audit'
        uses: actions/checkout@v3
        with:
          path: generator-jhipster-entity-audit
          fetch-depth: 2
      - name: 'SETUP: setup node'
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 'SETUP: install generator-jhister-entity-audit'
        run: |
          npm ci
          npm link
        working-directory: ${{ github.workspace }}/generator-jhipster-entity-audit
      - name: 'SETUP: get date'
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      - name: 'SETUP: load cache'
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress/
            ~/.m2/repository
          key: ${{ runner.os }}-app-${{ matrix.suite }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('generator-jhipster-entity-audit/package*.json') }}
      #----------------------------------------------------------------------
      # Install JHipster and generate project+entities
      #----------------------------------------------------------------------
      - name: 'PROJECT: generate'
        run: 'JHI_PROFILE=${{ matrix.profile }} jhipster-entity-audit generate-sample ${{ matrix.suite }} --build ${{ matrix.build-tool }} --audit-framework ${{ matrix.audit-framework }} --audit-page --no-insight --skip-git --skip-commit-hook --skip-jhipster-dependencies --no-cypress-audit --audit-update-type all'
      - name: 'TESTS: backend tests'
        run: npm run ci:backend:test
      - name: 'TESTS: frontend tests'
        run: npm run ci:frontend:test
      - name: 'TESTS: packaging'
        run: npm run ci:e2e:package
      - name: 'TESTS: start docker dependencies'
        run: npm run ci:e2e:prepare
        if: matrix.e2e != 'false'
      - name: 'TESTS: run e2e'
        run: npm run ci:e2e:run --if-present
        if: matrix.e2e != 'false'
  check-applications:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [applications]
    if: always()
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'
          if [ 'skipped' == '${{ needs.applications.result }}' ] || [ 'success' == '${{ needs.applications.result }}' ] || [ 'closed' == '${{ github.event.action }}' ]; then
            exit 0
          fi
          exit 1
